name: '🐞 - Bug Report'
title: '🐞 - '
description: Report a bug
labels: ['bug']

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which package(s) are the source of the bug?
      options:
        - '@taiga-ui/prettier-plugin-backticks'
      multiple: true
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Please provide the exception or error you saw.
        How do you trigger this bug?
        Please walk us through it step by step.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Please provide the actual behavior
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Please provide the expected behavior
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package version
      placeholder: x.y.z
    validations:
      required: true
