name: '🚀 - Feature Request'
title: '🚀 - '
description: Suggest a feature
labels: ['feature']

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which package(s) are the source of the bug?
      options:
        - '@taiga-ui/prettier-plugin-backticks'
      multiple: true
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Proposed solution.
        Alternatives considered.
    validations:
      required: true
