name: '📚 - Documentation'
title: '📚 - '
description: Report an issue in documentation
labels: ['documentation']

body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
