name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.55.5
      - uses: taiga-family/ci/actions/setup/variables@v1.55.5
      - uses: taiga-family/ci/actions/setup/node@v1.55.5

      - name: Run tests
        run: npm test

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
